spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_PASSWORD}

  liquibase:
    change-log: classpath:/db/changelog/app-changelog.yaml

identity:
  jwtExpirationInMs: ${JWT_EXPIRATION_IN_MS}
  jwtSecretKey: ${JWT_SECRET_KEY}